import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:pro_app/core/features/properties/data/property_model.dart';
import 'package:pro_app/core/features/properties/data/property_repository.dart';

// propertyRepoProvider -- DI
final propertyRepositoryProvider = Provider<PropertyRepository>((ref) {
  return PropertyRepository(FirebaseFirestore.instance);
});

// marketplaceProvider -- to display available properties(isPublished and available)
final marketPlaceProvider = StreamProvider.autoDispose<List<PropertyModel>>((
  ref,
) {
  // --- REAL IMPLEMENTATION ---
  // return ref.watch(propertyRepositoryProvider).watchPublished();

  // --- MOCK IMPLEMENTATION ---
  return Stream.fromFuture(
    Future.delayed(const Duration(seconds: 4), () => dummyProperties),
  );
});

// allPropertiesProvider
final allPropertiesProvider = StreamProvider.autoDispose<List<PropertyModel>>((
  ref,
) {
  return ref.watch(propertyRepositoryProvider).watchAll();
});

//propertyDetail provider
final propertyDetailProvider = FutureProvider.autoDispose
    .family<PropertyModel?, String>((ref, propertyId) async {
      // --- MOCK IMPLEMENTATION ---
      await Future.delayed(const Duration(milliseconds: 500));
      try {
        return dummyProperties.firstWhere((p) => p.id == propertyId);
      } catch (_) {
        return null;
      }

      // --- REAL IMPLEMENTATION ---
      // return ref.watch(propertyRepositoryProvider).getProperty(propertyId);
    });

// --- DUMMY DATA FOR TESTING ---
final dummyProperties = [
  PropertyModel(
    id: 'prop_1',
    title: 'Luxury 3-Bed Lekki Apartment',
    description:
        'A stunning modern apartment with ocean views and top-tier security.',
    address: 'Plot 12, Admiralty Way',
    city: 'Lekki Phase 1',
    state: 'Lagos',
    propertyType: PropertyType.apartment,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Swimming Pool', 'Gym', '24/7 Power'],
    imageUrls: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1000',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 10,
    availableUnit: 3,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_2',
    title: 'Cozy Studio in Yaba',
    description: 'Perfect for young professionals and creatives.',
    address: '24 Herbert Macaulay Way',
    city: 'Yaba',
    state: 'Lagos',
    propertyType: PropertyType.selfCon,
    rentPeriod: RentPeriod.monthly,
    amenities: ['Workspace', 'Security'],
    imageUrls: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 20,
    availableUnit: 12,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_3',
    title: '5-Bedroom Duplex Ikeja GRA',
    description: 'Spacious family home with a large garden.',
    address: '8 Isaac John Street',
    city: 'Ikeja GRA',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Garden', 'Parking', 'CCTV'],
    imageUrls: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_4',
    title: 'Eko Atlantic Penthouse',
    description: 'The height of luxury living with panoramic city views.',
    address: 'Tower A, Eko Atlantic City',
    city: 'Victoria Island',
    state: 'Lagos',
    propertyType: PropertyType.shortLet,
    rentPeriod: RentPeriod.nightly,
    amenities: ['Infinity Pool', 'Concierge', 'High-Speed Wifi'],
    imageUrls: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 2,
    availableUnit: 2,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_5',
    title: 'Commercial Office Space VI',
    description: 'Prime location for corporate headquarters.',
    address: '15 Akin Adesola Street',
    city: 'Victoria Island',
    state: 'Lagos',
    propertyType: PropertyType.commercial,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Underground Parking', 'Meeting Rooms', 'Backup Generator'],
    imageUrls: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_6',
    title: 'Banana Island Mansion',
    description: 'Ultra-private estate for high-net-worth individuals.',
    address: 'Zone 4, Banana Island',
    city: 'Ikoyi',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Private Jetty', 'Cinema Room', 'Wine Cellar'],
    imageUrls: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_7',
    title: 'Student Mini-flat Akoka',
    description: 'Clean and affordable housing near UNILAG.',
    address: '10 St. Finbarrs Road',
    city: 'Akoka',
    state: 'Lagos',
    propertyType: PropertyType.apartment,
    rentPeriod: RentPeriod.monthly,
    amenities: ['Prepaid Meter', 'Water Supply'],
    imageUrls: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 12,
    availableUnit: 4,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_8',
    title: 'Gbagada Terrace House',
    description: 'Peaceful residential neighborhood, ideal for families.',
    address: 'Medina Estate',
    city: 'Gbagada',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Uniformed Security', 'Good Road Network'],
    imageUrls: [
      'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 4,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_9',
    title: 'Surulere 2-Bed Flat',
    description:
        'Centrally located apartment with easy access to the Island and Mainland.',
    address: '32 Ogunlana Drive',
    city: 'Surulere',
    state: 'Lagos',
    propertyType: PropertyType.apartment,
    rentPeriod: RentPeriod.monthly,
    amenities: ['Borehole', 'Fenced Gate'],
    imageUrls: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 8,
    availableUnit: 2,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_10',
    title: 'Magodo Phase 2 Duplex',
    description: 'Executive duplex in a highly secured estate.',
    address: 'Plot 5, Bashiru Shittu Street',
    city: 'Magodo',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Street Lights', 'Waste Management', 'Security Patrol'],
    imageUrls: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_11',
    title: 'Ajah 4-Bedroom Terrace',
    description: 'Modern finishing in a newly developed estate.',
    address: 'Abraham Adesanya Estate',
    city: 'Ajah',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Fitted Kitchen', 'Car Port'],
    imageUrls: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 6,
    availableUnit: 2,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_12',
    title: 'Ikoyi Executive Suite',
    description: 'High-end suite for short stays and business travelers.',
    address: '12 Glover Road',
    city: 'Ikoyi',
    state: 'Lagos',
    propertyType: PropertyType.shortLet,
    rentPeriod: RentPeriod.nightly,
    amenities: ['Room Service', 'Bar', 'Laundry'],
    imageUrls: [
      'https://images.unsplash.com/photo-1590392847226-d90c4033870e?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 15,
    availableUnit: 5,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_13',
    title: 'Marina Shared Workspace',
    description: 'Modern office desk in the heart of the financial district.',
    address: 'Broad Street',
    city: 'Marina',
    state: 'Lagos',
    propertyType: PropertyType.commercial,
    rentPeriod: RentPeriod.monthly,
    amenities: ['AC', 'Internet', 'Receptionist'],
    imageUrls: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 50,
    availableUnit: 15,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_14',
    title: 'Ikorodu Family Bungalow',
    description: 'Quiet environment with plenty of space for expansion.',
    address: 'Odogunyan',
    city: 'Ikorodu',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Large Compound', 'Water Tank'],
    imageUrls: [
      'https://images.unsplash.com/photo-1464146072230-91cabc968266?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_15',
    title: 'Badagry Waterfront Villa',
    description: 'Scenic views and fresh air, perfect for weekend getaways.',
    address: 'Whispering Palms Area',
    city: 'Badagry',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.nightly,
    amenities: ['Water View', 'Beach Access'],
    imageUrls: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_16',
    title: 'Osapa London 3-Bed Duplex',
    description: 'Upscale living in a trendy neighborhood.',
    address: 'Osapa London Estate',
    city: 'Lekki',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Security Gate', 'Inverter'],
    imageUrls: [
      'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 2,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_17',
    title: 'Banana Island 2-Bed Flat',
    description: 'Luxury apartment in Nigerias most exclusive neighborhood.',
    address: 'Ocean View Towers',
    city: 'Banana Island',
    state: 'Lagos',
    propertyType: PropertyType.apartment,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Tennis Court', 'Pool', 'Elevator'],
    imageUrls: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 4,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_18',
    title: 'Sangotedo Smart Home',
    description: 'Control everything from your phone in this modern duplex.',
    address: 'Novare Mall Vicinity',
    city: 'Sangotedo',
    state: 'Lagos',
    propertyType: PropertyType.house,
    rentPeriod: RentPeriod.yearly,
    amenities: ['Smart Locks', 'Solar Panels'],
    imageUrls: [
      'https://images.unsplash.com/photo-1558036117-15d82a90b9b1?q=80&w=1000',
    ],
    isFurnished: false,
    isPublished: true,
    totalUnits: 1,
    availableUnit: 1,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_19',
    title: 'Ogba Renovated Loft',
    description: 'Stylish and modern interior in a bustling area.',
    address: 'Wempco Road',
    city: 'Ogba',
    state: 'Lagos',
    propertyType: PropertyType.apartment,
    rentPeriod: RentPeriod.monthly,
    amenities: ['AC', 'Modern Lighting'],
    imageUrls: [
      'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 5,
    availableUnit: 2,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  PropertyModel(
    id: 'prop_20',
    title: 'Epe Tropical Retreat',
    description: 'Escape the city noise in this eco-friendly lodge.',
    address: 'Alaro City Area',
    city: 'Epe',
    state: 'Lagos',
    propertyType: PropertyType.shortLet,
    rentPeriod: RentPeriod.nightly,
    amenities: ['Organic Garden', 'Solar Power'],
    imageUrls: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1000',
    ],
    isFurnished: true,
    isPublished: true,
    totalUnits: 10,
    availableUnit: 8,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
