// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHFawEw1G6e1PH7Y2puwEHKw4OyoyTEXY',
    appId: '1:824156037939:web:6e673a5e476e3617ae5446',
    messagingSenderId: '824156037939',
    projectId: 'proapp-8aa82',
    authDomain: 'proapp-8aa82.firebaseapp.com',
    storageBucket: 'proapp-8aa82.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rUx4ZN7-6Z8tN235eSjk4OvO9i6NX-Y',
    appId: '1:824156037939:android:e9ccd64ed0539fa3ae5446',
    messagingSenderId: '824156037939',
    projectId: 'proapp-8aa82',
    storageBucket: 'proapp-8aa82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhG_vr-YOK8woeP1GPMkaOB7W72dZUWSs',
    appId: '1:824156037939:ios:5043243a47e8aef1ae5446',
    messagingSenderId: '824156037939',
    projectId: 'proapp-8aa82',
    storageBucket: 'proapp-8aa82.firebasestorage.app',
    iosClientId: '824156037939-qi65pofsudnlhnumr95lcu325i969fmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.proApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHFawEw1G6e1PH7Y2puwEHKw4OyoyTEXY',
    appId: '1:824156037939:web:b6de7d419d3327beae5446',
    messagingSenderId: '824156037939',
    projectId: 'proapp-8aa82',
    authDomain: 'proapp-8aa82.firebaseapp.com',
    storageBucket: 'proapp-8aa82.firebasestorage.app',
  );
}
