// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNa5s4z4uXdXUitzkZ40Ifi_yHe4sR9P0',
    appId: '1:130839041947:web:c9a30a4b2434466995b33e',
    messagingSenderId: '130839041947',
    projectId: 'proapp-a7ad0',
    authDomain: 'proapp-a7ad0.firebaseapp.com',
    storageBucket: 'proapp-a7ad0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMan7WU0wN--TD5RiBPICl3jIamxtWfsY',
    appId: '1:130839041947:android:37a898417ac4b79b95b33e',
    messagingSenderId: '130839041947',
    projectId: 'proapp-a7ad0',
    storageBucket: 'proapp-a7ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8uoJaOJl0KOinoVPbYoBNAZKfXf2YMLo',
    appId: '1:130839041947:ios:1825f5e0fea2ca8b95b33e',
    messagingSenderId: '130839041947',
    projectId: 'proapp-a7ad0',
    storageBucket: 'proapp-a7ad0.firebasestorage.app',
    iosClientId: '130839041947-ch8minu30vq9fshtgvj219a514olq2hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.proApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNa5s4z4uXdXUitzkZ40Ifi_yHe4sR9P0',
    appId: '1:130839041947:web:58536e10df5b76ae95b33e',
    messagingSenderId: '130839041947',
    projectId: 'proapp-a7ad0',
    authDomain: 'proapp-a7ad0.firebaseapp.com',
    storageBucket: 'proapp-a7ad0.firebasestorage.app',
  );
}
