// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:pro_app/core/features/properties/data/property_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PropertyModelAdapter());
    registerAdapter(PropertyTypeAdapter());
    registerAdapter(RentPeriodAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PropertyModelAdapter());
    registerAdapter(PropertyTypeAdapter());
    registerAdapter(RentPeriodAdapter());
  }
}
